#spring.application.name=hospitalManagement
#
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB
#spring.datasource.username=postgres
#spring.datasource.password=Patel
#
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
##insert static data then these properties are needed
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql
#update only used in devlopment
# in production we are used => validate -< they dont allow to create new row and column existing database that dont run the code if u changes any with database  , none -> matlb aap data base ke sath kuc bhi chnages kro like add new column and row they dont affet actual database

spring.application.name=hospitalManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB
spring.datasource.username=postgres
spring.datasource.password=Patel

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql